class_name UIForgeTypes
extends RefCounted

const SCHEMA_VERSION: int = 1
const GENERATED_MARKER: String = "GENERATED BY UIForge - EDIT THE .ui.json SOURCE DOCUMENT INSTEAD"
const STATES: Array[String] = ["normal", "hover", "pressed", "focused", "disabled", "selected"]
const VIEWPORT_PRESETS: Array[Vector2i] = [
	Vector2i(1280, 720),
	Vector2i(1600, 900), Vector2i(1920, 1080),
	Vector2i(2560, 1440), Vector2i(3840, 2160)
]
const NATIVE_TYPES: Array[String] = [
	"Control", "Panel", "Label", "RichText", "Texture", "Button", "TextureButton",
	"CheckBox", "CheckButton", "Slider", "HSlider", "VSlider", "SpinBox", "ProgressBar", "LineEdit",
	"TextEdit", "OptionButton", "MenuButton", "LinkButton", "ScrollContainer", "Grid", "HBox",
	"VBox", "MarginContainer", "CenterContainer", "PanelContainer", "TabBar", "TabContainer",
	"TabButton", "AspectRatioContainer", "FlowContainer", "HSplitContainer", "VSplitContainer",
	"ColorRect", "NinePatchRect", "Separator", "Spacer"
]
const COMPONENT_TYPES: Array[String] = [
	"WindowFrame", "OrnatePanel", "SimplePanel", "SectionPanel", "PrimaryButton",
	"SecondaryButton", "IconButton", "TabBar", "TabButton", "ItemSlot", "ItemGrid",
	"EquipmentSlot", "EquipmentLayout", "InventoryPanel", "BankPanel", "QuestEntry",
	"QuestList", "ScrollList", "Tooltip", "ContextMenu", "ContextMenuEntry", "ModalDialog",
	"ProgressDisplay", "StatusBar", "CurrencyDisplay", "SearchBox", "Dropdown", "CheckToggle", "SidebarNavigation",
	"SidebarEntry", "GameplaySidebar", "GameplaySidebarTab", "GameplaySidebarToggle", "EnemyTargetFrame", "EnemyTargetHealthBar", "EnemyStatusEffect", "CharacterPreviewFrame", "NotificationToast", "LootPopup", "CombatHUD",
	"ResourceBar", "HealthBar", "PrayerBar", "RunBar", "SpecialBar", "HUDMedallion", "ActionSlot"
]
const CONTAINER_TYPES: Array[String] = [
	"Control", "Panel", "WindowFrame", "OrnatePanel", "SimplePanel", "SectionPanel",
	"ScrollContainer", "Grid", "HBox", "VBox", "MarginContainer", "CenterContainer",
	"PanelContainer", "TabBar", "TabContainer", "AspectRatioContainer", "FlowContainer", "HSplitContainer", "VSplitContainer",
	"ItemGrid", "EquipmentLayout", "InventoryPanel", "BankPanel", "QuestList",
	"ScrollList", "SidebarNavigation", "GameplaySidebar", "EnemyTargetFrame", "CharacterPreviewFrame", "ModalDialog", "CombatHUD", "HUDMedallion"
]
const INTERACTIVE_TYPES: Array[String] = [
	"Button", "TextureButton", "CheckBox", "CheckButton", "Slider", "HSlider", "VSlider", "SpinBox", "LineEdit", "TextEdit", "OptionButton", "MenuButton", "LinkButton", "PrimaryButton",
	"SecondaryButton", "IconButton", "TabButton", "ItemSlot", "ContextMenuEntry", "SidebarEntry", "GameplaySidebarTab", "GameplaySidebarToggle", "ActionSlot"
]
