#!/usr/bin/env python3
"""Shared filesystem, provenance, and safety contracts for the portable CLI."""

from __future__ import annotations

import hashlib
import json
import os
import re
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
GENERATED_MARKER = "GENERATED BY UIForge - EDIT THE .ui.json SOURCE DOCUMENT INSTEAD"
HEADER_VERSION = "UIFORGE_GENERATED_V1"
GENERATOR_VERSION = "uiforge/0.1.0"
SCHEMA_VERSION = 1
METADATA_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
RESERVED_PREFIXES = ("uiforge_", "aether_")
GENERATED_METADATA_KEYS = {
    "uiforge_id", "uiforge_type", "uiforge_generated", "uiforge_action", "uiforge_binding",
    "uiforge_transitions", "uiforge_effects", "uiforge_decoration",
    "aether_id", "aether_type", "aether_generated", "aether_action", "aether_binding",
    "aether_transitions", "aether_effects", "aether_decoration",
}
ALLOWED_RESOURCE_TYPES = {
    "Texture2D", "CompressedTexture2D", "ImageTexture", "AtlasTexture", "FontFile",
    "FontVariation", "Theme", "Material", "ShaderMaterial", "CanvasItemMaterial",
    "LabelSettings", "Shortcut", "ButtonGroup", "StyleBoxFlat", "StyleBoxTexture",
}
BLOCKED_RESOURCE_TYPES = {"Script", "GDScript", "CSharpScript", "PackedScene", "Shader"}


def workspace_root() -> Path:
    return ROOT.resolve()


def fs_path(raw: str | Path) -> Path:
    value = str(raw)
    if value.startswith("res://"):
        return (ROOT / value.removeprefix("res://")).resolve()
    return Path(value).expanduser().resolve()


def project_relative(absolute: Path) -> str:
    root = workspace_root()
    try:
        relative = absolute.resolve().relative_to(root)
    except ValueError:
        return str(absolute).replace("\\", "/")
    return f"res://{relative.as_posix()}"


def validate_output(path: str | Path, extension: str, allow_outside_project: bool = False) -> dict[str, Any]:
    absolute = fs_path(path)
    errors: list[dict[str, Any]] = []
    if not str(path).endswith(extension):
        errors.append({
            "code": "OUTPUT_EXTENSION_INVALID",
            "message": f"Output '{path}' must use extension {extension}.",
            "path": str(path),
        })
    if not allow_outside_project:
        root = workspace_root()
        try:
            absolute.relative_to(root)
        except ValueError:
            errors.append({
                "code": "OUTPUT_OUTSIDE_WORKSPACE",
                "message": f"Output '{path}' is outside the project workspace. Pass --allow-outside-project to override.",
                "path": str(path),
            })
    return {"ok": not errors, "absolute": absolute, "project_relative": project_relative(absolute), "errors": errors}


def canonical_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def content_hash(data: dict[str, Any]) -> str:
    return f"sha256:{hashlib.sha256(canonical_json(data).encode('utf-8')).hexdigest()}"


def file_revision(path: str | Path) -> dict[str, Any]:
    absolute = fs_path(path)
    if not absolute.exists():
        return {"ok": False, "hash": "", "errors": [{"code": "FILE_NOT_FOUND", "message": str(path)}]}
    try:
        payload = json.loads(absolute.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return {"ok": False, "hash": "", "errors": [{"code": "JSON_PARSE_ERROR", "message": str(exc), "line": exc.lineno}]}
    if not isinstance(payload, dict):
        return {"ok": False, "hash": "", "errors": [{"code": "DOCUMENT_NOT_OBJECT", "message": "The document root must be an object."}]}
    return {"ok": True, "hash": content_hash(payload), "errors": []}


def provenance_header(source_identity: str, source_hash: str) -> list[str]:
    return [
        f"; {HEADER_VERSION}",
        f"; uiforge_source: {source_identity}",
        f"; uiforge_source_hash: {source_hash}",
        f"; uiforge_generator: {GENERATOR_VERSION}",
        f"; uiforge_schema: {SCHEMA_VERSION}",
        f"; {GENERATED_MARKER}",
    ]


def parse_scene_header(text: str) -> dict[str, Any]:
    result = {"is_uiforge": False, "source": "", "source_hash": "", "generator": "", "schema": -1}
    for line in text.splitlines():
        trimmed = line.strip()
        if not trimmed.startswith(";"):
            break
        if trimmed == f"; {HEADER_VERSION}":
            result["is_uiforge"] = True
        elif trimmed.startswith("; uiforge_source:"):
            result["source"] = trimmed.split(":", 1)[1].strip()
        elif trimmed.startswith("; uiforge_source_hash:"):
            result["source_hash"] = trimmed.split(":", 1)[1].strip()
        elif trimmed.startswith("; uiforge_generator:"):
            result["generator"] = trimmed.split(":", 1)[1].strip()
        elif trimmed.startswith("; uiforge_schema:"):
            result["schema"] = int(trimmed.split(":", 1)[1].strip())
    return result


def source_identity(source_path: str | Path) -> str:
    absolute = fs_path(source_path)
    return project_relative(absolute)


def check_create_allowed(path: str | Path, force: bool) -> dict[str, Any]:
    absolute = fs_path(path)
    if force or not absolute.exists():
        return {"ok": True, "errors": []}
    return {
        "ok": False,
        "errors": [{
            "code": "OUTPUT_ALREADY_EXISTS",
            "message": f"Refusing to overwrite existing '{path}'. Pass --force to replace it.",
            "path": str(path),
        }],
    }


def check_replace_allowed(output_path: str | Path, source_identity_value: str, source_hash: str, force: bool) -> dict[str, Any]:
    if force:
        return {"ok": True, "errors": []}
    absolute = fs_path(output_path)
    if not absolute.exists():
        return {"ok": True, "errors": []}
    header = parse_scene_header(absolute.read_text(encoding="utf-8"))
    if not header.get("is_uiforge"):
        return {
            "ok": False,
            "errors": [{
                "code": "OUTPUT_NOT_UIFORGE_GENERATED",
                "message": f"Refusing to overwrite '{output_path}' because it is not a UIForge-generated artifact. Pass --force to override.",
                "path": str(output_path),
            }],
        }
    if header.get("source") != source_identity_value or header.get("source_hash") != source_hash:
        return {
            "ok": False,
            "errors": [{
                "code": "OUTPUT_SOURCE_MISMATCH",
                "message": f"Refusing to overwrite '{output_path}' generated from a different source. Pass --force to override.",
                "path": str(output_path),
                "existing_source": header.get("source", ""),
                "requested_source": source_identity_value,
            }],
        }
    return {"ok": True, "errors": []}


def unique_temp_path(absolute: Path) -> Path:
    nonce = f"{time.time_ns()}_{os.getpid()}"
    return absolute.parent / f".uiforge_tmp_{absolute.name}_{nonce}"


def write_text_atomically(target_path: str | Path, content: str, verify=None) -> dict[str, Any]:
    absolute = fs_path(target_path)
    absolute.parent.mkdir(parents=True, exist_ok=True)
    temp_path = unique_temp_path(absolute)
    try:
        temp_path.write_text(content, encoding="utf-8")
        if verify is not None:
            verify_result = verify(temp_path)
            if not verify_result.get("ok", True):
                return {"success": False, "committed": False, "errors": verify_result.get("errors", [])}
        os.replace(temp_path, absolute)
    except OSError as exc:
        if temp_path.exists():
            temp_path.unlink(missing_ok=True)
        return {"success": False, "committed": False, "errors": [{"code": "FILE_WRITE_FAILED", "message": str(exc)}]}
    return {"success": True, "committed": True, "path": str(target_path), "errors": []}


def recover_interrupted_source(absolute: Path) -> None:
    backup_path = absolute.with_name(absolute.name + ".uiforge_backup")
    pending_path = absolute.with_name(absolute.name + ".uiforge_pending")
    if pending_path.exists():
        if absolute.exists():
            absolute.unlink()
        os.replace(pending_path, absolute)
    elif not absolute.exists() and backup_path.exists():
        os.replace(backup_path, absolute)


def write_source_atomically(target_path: str | Path, content: str, expected_revision: str = "") -> dict[str, Any]:
    absolute = fs_path(target_path)
    backup_path = absolute.with_name(absolute.name + ".uiforge_backup")
    pending_path = absolute.with_name(absolute.name + ".uiforge_pending")
    recover_interrupted_source(absolute)
    if expected_revision and absolute.exists():
        current = file_revision(target_path)
        if not current.get("ok"):
            return {"success": False, "committed": False, "errors": current.get("errors", [])}
        if current.get("hash") != expected_revision:
            return {
                "success": False,
                "committed": False,
                "errors": [{
                    "code": "WRITE_CONFLICT",
                    "message": f"Source changed since it was loaded; refusing to overwrite {target_path}.",
                    "path": str(target_path),
                }],
            }
    temp_path = unique_temp_path(absolute)
    try:
        absolute.parent.mkdir(parents=True, exist_ok=True)
        temp_path.write_text(content, encoding="utf-8")
        if absolute.exists():
            if backup_path.exists():
                backup_path.unlink()
            os.replace(absolute, backup_path)
        os.replace(temp_path, pending_path)
        os.replace(pending_path, absolute)
        if backup_path.exists():
            backup_path.unlink()
    except OSError as exc:
        if backup_path.exists() and not absolute.exists():
            os.replace(backup_path, absolute)
        temp_path.unlink(missing_ok=True)
        pending_path.unlink(missing_ok=True)
        return {"success": False, "committed": False, "errors": [{"code": "FILE_WRITE_FAILED", "message": str(exc)}]}
    return {"success": True, "committed": True, "path": str(target_path), "errors": []}


def verify_scene_syntax(temp_path: Path) -> dict[str, Any]:
    text = temp_path.read_text(encoding="utf-8")
    if "[gd_scene" not in text:
        return {"ok": False, "errors": [{"code": "SCENE_SYNTAX_INVALID", "message": "Generated scene is missing [gd_scene] header."}]}
    header = parse_scene_header(text)
    if not header.get("is_uiforge"):
        return {"ok": False, "errors": [{"code": "SCENE_PROVENANCE_INVALID", "message": "Generated scene is missing UIForge provenance header."}]}
    return {"ok": True, "errors": []}


def validate_authored_metadata_key(key: str) -> dict[str, Any]:
    name = str(key)
    if not name or not METADATA_IDENTIFIER.fullmatch(name):
        return {"severity": "error", "code": "METADATA_KEY_INVALID", "message": f"Metadata key '{name}' must be a Godot-safe identifier.", "node": name}
    if name.startswith(RESERVED_PREFIXES) or name in GENERATED_METADATA_KEYS:
        return {"severity": "error", "code": "METADATA_KEY_RESERVED", "message": f"Metadata key '{name}' uses a reserved namespace.", "node": name}
    return {}


def validate_godot_override(property_name: str, allow_unsafe: bool = False) -> dict[str, Any]:
    name = str(property_name)
    if not name or any(ch in name for ch in "\n\r="):
        return {"severity": "error", "code": "GODOT_OVERRIDE_INVALID", "message": f"Property path '{name}' contains invalid syntax.", "node": ""}
    if name.startswith("metadata/"):
        return {"severity": "error", "code": "GODOT_OVERRIDE_FORBIDDEN", "message": "Cannot write metadata through godot_overrides.", "node": ""}
    lowered = name.lower()
    if "script" in lowered or name in GENERATED_METADATA_KEYS:
        return {"severity": "error", "code": "GODOT_OVERRIDE_UNSAFE", "message": f"Property '{name}' is blocked by default.", "node": ""}
    if name.startswith("theme_override_") and "/" in name:
        return {}
    if "/" in name:
        return {"severity": "error", "code": "GODOT_OVERRIDE_UNKNOWN", "message": f"Unknown or unsupported property path '{name}'.", "node": ""}
    return {}


def resource_id_part(value: str) -> str:
    canonical = str(value)
    if not canonical:
        return "node"
    return canonical.replace("_", "__").replace("-", "_-")


def validate_external_resource(path: str, resource_type: str, property_name: str, allow_unsafe: bool = False) -> dict[str, Any]:
    if not path.startswith("res://") or any(ch in path for ch in "\n\r\""):
        return {"severity": "error", "code": "RESOURCE_PATH_INVALID", "message": "External resource path must begin with res://.", "node": ""}
    if not allow_unsafe and resource_type in BLOCKED_RESOURCE_TYPES:
        return {"severity": "error", "code": "RESOURCE_TYPE_BLOCKED", "message": f"Resource type '{resource_type}' is blocked by default.", "node": ""}
    if not allow_unsafe and "script" in property_name.lower():
        return {"severity": "error", "code": "RESOURCE_TYPE_BLOCKED", "message": f"Resource property '{property_name}' is blocked by default.", "node": ""}
    if resource_type and resource_type not in ALLOWED_RESOURCE_TYPES and not allow_unsafe:
        return {"severity": "error", "code": "RESOURCE_TYPE_UNKNOWN", "message": f"Resource type '{resource_type}' is not in the UIForge whitelist.", "node": ""}
    return {}


def available_theme_names() -> list[str]:
    theme_dir = ROOT / "addons/uiforge/themes"
    if not theme_dir.exists():
        return []
    return sorted(path.name.removesuffix(".theme.json") for path in theme_dir.glob("*.theme.json"))


def load_theme_checked(theme_name: str) -> dict[str, Any]:
    normalized = str(theme_name).strip()
    if not normalized:
        return {"theme": None, "errors": [{"severity": "error", "code": "THEME_NOT_FOUND", "message": "Document theme name is required."}]}
    path = ROOT / f"addons/uiforge/themes/{normalized}.theme.json"
    if not path.exists():
        return {
            "theme": None,
            "errors": [{
                "severity": "error",
                "code": "THEME_NOT_FOUND",
                "message": f"Theme '{normalized}' was not found.",
                "recommendation": f"Choose one of: {', '.join(available_theme_names())}.",
            }],
        }
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return {"theme": None, "errors": [{"severity": "error", "code": "THEME_PARSE_ERROR", "message": str(exc), "line": exc.lineno}]}
    if not isinstance(payload, dict):
        return {"theme": None, "errors": [{"severity": "error", "code": "THEME_PARSE_ERROR", "message": "Theme file must contain an object."}]}
    return {"theme": payload, "errors": []}
