#!/usr/bin/env python3
"""Shared filesystem, provenance, and safety contracts for the portable CLI."""

from __future__ import annotations

import hashlib
import json
import os
import re
import secrets
import shutil
import socket
import time
from pathlib import Path, PureWindowsPath
from typing import Any, Callable

ROOT = Path(__file__).resolve().parents[1]
GENERATED_MARKER = "GENERATED BY UIForge - EDIT THE .ui.json SOURCE DOCUMENT INSTEAD"
HEADER_VERSION = "UIFORGE_GENERATED_V1"
GENERATOR_VERSION = "uiforge/0.1.0"
SCHEMA_VERSION = 1
MAX_HEADER_LINES = 32
HASH_PATTERN = re.compile(r"^sha256:[0-9a-f]{64}$")
THEME_IDENTIFIER = re.compile(r"^[A-Za-z0-9_-]+$")
METADATA_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
RESERVED_PREFIXES = ("uiforge_", "aether_")
GENERATED_METADATA_KEYS = {
    "uiforge_id", "uiforge_type", "uiforge_generated", "uiforge_action", "uiforge_binding",
    "uiforge_transitions", "uiforge_effects", "uiforge_decoration",
    "aether_id", "aether_type", "aether_generated", "aether_action", "aether_binding",
    "aether_transitions", "aether_effects", "aether_decoration",
}
ALLOWED_RESOURCE_TYPES = {
    "Texture2D", "CompressedTexture2D", "ImageTexture", "AtlasTexture", "FontFile",
    "FontVariation", "Theme", "Material", "ShaderMaterial", "CanvasItemMaterial",
    "LabelSettings", "Shortcut", "ButtonGroup", "StyleBoxFlat", "StyleBoxTexture",
}
BLOCKED_RESOURCE_TYPES = {"Script", "GDScript", "CSharpScript", "PackedScene", "Shader"}
BLOCKED_RESOURCE_EXTENSIONS = {".gd", ".cs", ".tscn", ".scn", ".shader", ".gdshader"}
FALLBACK_COMPATIBILITY: dict[str, set[str]] = {
    "Texture2D": {"CompressedTexture2D", "ImageTexture", "AtlasTexture", "PortableCompressedTexture2D"},
    "FontFile": {"FontVariation"},
    "Material": {"ShaderMaterial", "CanvasItemMaterial"},
    "StyleBoxFlat": {"StyleBoxTexture", "StyleBoxEmpty"},
}
LOCK_STALE_SECONDS = 300
NEW_LOCK_GRACE_SECONDS = 5
GODOT_ID_PATTERN = re.compile(r"^[A-Za-z0-9_]+$")
SCENE_ID_PATTERN = re.compile(r'id="([^"]+)"')


def workspace_root() -> Path:
    return ROOT.resolve()


def is_absolute_requested(value: str) -> bool:
    if value.startswith("res://") or value.startswith("user://"):
        return False
    if PureWindowsPath(value).is_absolute():
        return True
    return Path(value).expanduser().is_absolute()


def fs_path(raw: str | Path) -> Path:
    value = str(raw).strip()
    if value.startswith("res://"):
        return resolve_real_path((ROOT / value.removeprefix("res://")))
    path = Path(value).expanduser()
    if is_absolute_requested(value):
        return resolve_real_path(path)
    return resolve_real_path(ROOT / value)


def resolve_real_path(absolute: Path) -> Path:
    try:
        return absolute.resolve()
    except OSError:
        return absolute


def project_relative(absolute: Path) -> str:
    root = workspace_root()
    resolved = resolve_real_path(absolute)
    try:
        relative = resolved.relative_to(root)
    except ValueError:
        return str(resolved).replace("\\", "/")
    return f"res://{relative.as_posix()}"


def validate_output(path: str | Path, extension: str, allow_outside_project: bool = False) -> dict[str, Any]:
    absolute = fs_path(path)
    errors: list[dict[str, Any]] = []
    if not str(path).endswith(extension):
        errors.append({
            "code": "OUTPUT_EXTENSION_INVALID",
            "message": f"Output '{path}' must use extension {extension}.",
            "path": str(path),
        })
    if not allow_outside_project:
        root = workspace_root()
        try:
            resolve_real_path(absolute).relative_to(root)
        except ValueError:
            errors.append({
                "code": "OUTPUT_OUTSIDE_WORKSPACE",
                "message": f"Output '{path}' is outside the project workspace. Pass --allow-outside-project to override.",
                "path": str(path),
            })
    return {"ok": not errors, "absolute": absolute, "project_relative": project_relative(absolute), "errors": errors}


def canonical_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def content_hash(data: dict[str, Any]) -> str:
    return f"sha256:{hashlib.sha256(canonical_json(data).encode('utf-8')).hexdigest()}"


def file_revision(path: str | Path) -> dict[str, Any]:
    absolute = fs_path(path)
    if not absolute.exists():
        return {"ok": False, "hash": "", "errors": [{"code": "FILE_NOT_FOUND", "message": str(path)}]}
    try:
        payload = json.loads(absolute.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return {"ok": False, "hash": "", "errors": [{"code": "JSON_PARSE_ERROR", "message": str(exc), "line": exc.lineno}]}
    if not isinstance(payload, dict):
        return {"ok": False, "hash": "", "errors": [{"code": "DOCUMENT_NOT_OBJECT", "message": "The document root must be an object."}]}
    return {"ok": True, "hash": content_hash(payload), "errors": []}


def provenance_header(source_identity: str, source_hash: str) -> list[str]:
    return [
        f"; {HEADER_VERSION}",
        f"; uiforge_source: {source_identity}",
        f"; uiforge_source_hash: {source_hash}",
        f"; uiforge_generator: {GENERATOR_VERSION}",
        f"; uiforge_schema: {SCHEMA_VERSION}",
        f"; {GENERATED_MARKER}",
    ]


def _parse_error(code: str, message: str) -> dict[str, Any]:
    return {"code": code, "message": message}


def validate_provenance(header: dict[str, Any]) -> list[dict[str, Any]]:
    errors: list[dict[str, Any]] = []
    version = str(header.get("version", ""))
    if version != HEADER_VERSION:
        errors.append(_parse_error("OUTPUT_PROVENANCE_INVALID", f"Unsupported provenance version '{version}'."))
    if not str(header.get("source", "")):
        errors.append(_parse_error("OUTPUT_PROVENANCE_INVALID", "Missing uiforge_source."))
    hash_value = str(header.get("source_hash", ""))
    if not hash_value:
        errors.append(_parse_error("OUTPUT_PROVENANCE_INVALID", "Missing uiforge_source_hash."))
    elif HASH_PATTERN.fullmatch(hash_value) is None:
        errors.append(_parse_error("OUTPUT_PROVENANCE_INVALID", "Malformed uiforge_source_hash."))
    if not str(header.get("generator", "")):
        errors.append(_parse_error("OUTPUT_PROVENANCE_INVALID", "Missing uiforge_generator."))
    schema = int(header.get("schema", -1))
    if schema < 0:
        errors.append(_parse_error("OUTPUT_PROVENANCE_INVALID", "Missing or malformed uiforge_schema."))
    return errors


def parse_scene_header(text: str | bytes | None) -> dict[str, Any]:
    header: dict[str, Any] = {
        "is_uiforge": False,
        "version": "",
        "source": "",
        "source_hash": "",
        "generator": "",
        "schema": -1,
        "trusted": False,
    }
    errors: list[dict[str, Any]] = []
    if text is None:
        errors.append(_parse_error("OUTPUT_READ_FAILED", "Output text was null."))
        return {"ok": False, "header": header, "errors": errors}
    if isinstance(text, bytes):
        try:
            raw = text.decode("utf-8")
        except UnicodeDecodeError as exc:
            errors.append(_parse_error("OUTPUT_READ_FAILED", f"Output is not valid UTF-8: {exc}"))
            return {"ok": False, "header": header, "errors": errors}
    else:
        raw = text
    if not raw:
        return {"ok": True, "header": header, "errors": errors}
    duplicate_versions = duplicate_sources = duplicate_hashes = duplicate_generators = duplicate_schemas = 0
    comment_lines = 0
    for line in raw.splitlines():
        trimmed = line.strip()
        if not trimmed.startswith(";"):
            break
        comment_lines += 1
        if comment_lines > MAX_HEADER_LINES:
            errors.append(_parse_error("OUTPUT_PROVENANCE_INVALID", "Provenance preamble exceeds supported size."))
            break
        if trimmed.startswith("; UIFORGE_GENERATED_V") and trimmed != f"; {HEADER_VERSION}":
            duplicate_versions += 1
            header["is_uiforge"] = True
            header["version"] = trimmed[2:].strip()
            errors.append(_parse_error("OUTPUT_PROVENANCE_INVALID", f"Unsupported provenance version '{header['version']}'."))
        elif trimmed == f"; {HEADER_VERSION}":
            duplicate_versions += 1
            header["is_uiforge"] = True
            header["version"] = HEADER_VERSION
        elif trimmed.startswith("; uiforge_source:"):
            duplicate_sources += 1
            header["source"] = trimmed.split(":", 1)[1].strip()
        elif trimmed.startswith("; uiforge_source_hash:"):
            duplicate_hashes += 1
            header["source_hash"] = trimmed.split(":", 1)[1].strip()
        elif trimmed.startswith("; uiforge_generator:"):
            duplicate_generators += 1
            header["generator"] = trimmed.split(":", 1)[1].strip()
        elif trimmed.startswith("; uiforge_schema:"):
            duplicate_schemas += 1
            schema_text = trimmed.split(":", 1)[1].strip()
            if not schema_text.isdigit():
                errors.append(_parse_error("OUTPUT_PROVENANCE_INVALID", "Malformed uiforge_schema value."))
            else:
                header["schema"] = int(schema_text)
    if duplicate_versions > 1 or duplicate_sources > 1 or duplicate_hashes > 1 or duplicate_generators > 1 or duplicate_schemas > 1:
        errors.append(_parse_error("OUTPUT_PROVENANCE_INVALID", "Duplicate provenance header fields."))
    if header.get("is_uiforge"):
        errors.extend(validate_provenance(header))
    header["trusted"] = bool(header.get("is_uiforge")) and not errors
    return {"ok": not errors, "header": header, "errors": errors}


def read_existing_output(output_path: str | Path) -> dict[str, Any]:
    absolute = fs_path(output_path)
    if not absolute.exists():
        return {"ok": True, "exists": False, "text": "", "header": {}, "errors": []}
    try:
        text = absolute.read_text(encoding="utf-8")
    except OSError as exc:
        return {"ok": False, "errors": [{"code": "OUTPUT_OPEN_FAILED", "message": str(exc), "path": str(output_path)}]}
    parsed = parse_scene_header(text)
    if not parsed.get("ok", False):
        return {"ok": False, "exists": True, "text": text, "header": parsed.get("header", {}), "errors": parsed.get("errors", [])}
    return {"ok": True, "exists": True, "text": text, "header": parsed.get("header", {}), "errors": []}


def source_identity(source_path: str | Path) -> str:
    absolute = fs_path(source_path)
    return project_relative(absolute)


def check_create_allowed(path: str | Path, force: bool) -> dict[str, Any]:
    absolute = fs_path(path)
    if force or not absolute.exists():
        return {"ok": True, "errors": []}
    return {
        "ok": False,
        "errors": [{
            "code": "OUTPUT_ALREADY_EXISTS",
            "message": f"Refusing to overwrite existing '{path}'. Pass --force to replace it.",
            "path": str(path),
        }],
    }


def check_replace_allowed(output_path: str | Path, source_identity_value: str, _source_hash: str, force: bool) -> dict[str, Any]:
    if force:
        return {"ok": True, "errors": []}
    existing = read_existing_output(output_path)
    if not existing.get("ok", False):
        return {"ok": False, "errors": existing.get("errors", [])}
    if not existing.get("exists", False):
        return {"ok": True, "errors": []}
    header = existing.get("header", {})
    if not header.get("is_uiforge"):
        return {
            "ok": False,
            "errors": [{
                "code": "OUTPUT_NOT_UIFORGE_GENERATED",
                "message": f"Refusing to overwrite '{output_path}' because it is not a UIForge-generated artifact. Pass --force to override.",
                "path": str(output_path),
            }],
        }
    if not header.get("trusted", False):
        return {
            "ok": False,
            "errors": existing.get("errors", [{
                "code": "OUTPUT_PROVENANCE_INVALID",
                "message": f"Existing output '{output_path}' has invalid UIForge provenance.",
                "path": str(output_path),
            }]),
        }
    existing_source = str(header.get("source", ""))
    if existing_source != source_identity_value:
        return {
            "ok": False,
            "errors": [{
                "code": "OUTPUT_SOURCE_MISMATCH",
                "message": f"Refusing to overwrite '{output_path}' generated from a different source. Pass --force to override.",
                "path": str(output_path),
                "existing_source": existing_source,
                "requested_source": source_identity_value,
            }],
        }
    return {"ok": True, "errors": []}


def check_commit_replace_allowed(output_path: str | Path, source_identity_value: str, force: bool) -> dict[str, Any]:
    return check_replace_allowed(output_path, source_identity_value, "", force)


def unique_temp_path(absolute: Path, extension: str = "") -> Path:
    nonce = f"{time.time_ns()}_{os.getpid()}"
    suffix = extension or absolute.suffix
    if suffix and not suffix.startswith("."):
        suffix = f".{suffix}"
    stem = absolute.stem if absolute.suffix else absolute.name
    return absolute.parent / f".uiforge_tmp_{stem}_{nonce}{suffix}"


def _lock_dir(target_absolute: Path) -> Path:
    return target_absolute.with_name(target_absolute.name + ".uiforge_lock")


def _write_lock_meta(lock_dir: Path, owner_nonce: str) -> None:
    payload = {
        "owner_nonce": owner_nonce,
        "pid": os.getpid(),
        "started": time.time(),
        "hostname": socket.gethostname(),
    }
    (lock_dir / "owner.json").write_text(json.dumps(payload), encoding="utf-8")


def _read_lock_meta(lock_dir: Path) -> dict[str, Any]:
    owner_path = lock_dir / "owner.json"
    if not owner_path.exists():
        return {}
    try:
        payload = json.loads(owner_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _remove_lock_dir(lock_dir: Path) -> None:
    if lock_dir.exists():
        shutil.rmtree(lock_dir, ignore_errors=True)


def _pid_alive(pid: int) -> bool:
    if pid <= 0:
        return False
    if os.name == "nt":
        return True
    return Path(f"/proc/{pid}").exists()


def _lock_is_stale(lock_dir: Path) -> bool:
    if not lock_dir.exists():
        return False
    meta = _read_lock_meta(lock_dir)
    started = float(meta.get("started", 0))
    age = time.time() - started if started > 0 else NEW_LOCK_GRACE_SECONDS + 1
    if age < NEW_LOCK_GRACE_SECONDS:
        return False
    if meta:
        pid = int(meta.get("pid", 0))
        if pid > 0 and _pid_alive(pid) and age < LOCK_STALE_SECONDS:
            return False
    if age < LOCK_STALE_SECONDS and not meta:
        return False
    return True


def _try_reclaim_stale_lock(lock_dir: Path) -> bool:
    if not _lock_is_stale(lock_dir):
        return False
    reclaim_path = lock_dir.with_name(f"{lock_dir.name}.reclaim_{secrets.token_hex(8)}")
    try:
        os.replace(lock_dir, reclaim_path)
    except OSError:
        return False
    _remove_lock_dir(reclaim_path)
    return True


def acquire_lock(target_absolute: Path) -> dict[str, Any]:
    lock_dir = _lock_dir(target_absolute)
    owner_nonce = secrets.token_hex(16)
    for attempt in range(4):
        try:
            lock_dir.mkdir()
            try:
                _write_lock_meta(lock_dir, owner_nonce)
            except OSError:
                _remove_lock_dir(lock_dir)
                raise
            return {"ok": True, "lock_path": lock_dir, "owner_nonce": owner_nonce}
        except FileExistsError:
            if _try_reclaim_stale_lock(lock_dir):
                continue
            time.sleep(0.025 * (attempt + 1))
        except OSError as exc:
            return {
                "ok": False,
                "errors": [{
                    "code": "LOCK_CREATE_FAILED",
                    "message": str(exc),
                    "path": str(target_absolute),
                }],
            }
    return {
        "ok": False,
        "errors": [{
            "code": "WRITE_CONFLICT",
            "message": f"Could not acquire commit lock for {target_absolute}.",
            "path": str(target_absolute),
        }],
    }


def release_lock(lock_path: Path | None, owner_nonce: str = "") -> None:
    if lock_path is None or not owner_nonce or not lock_path.exists():
        return
    meta = _read_lock_meta(lock_path)
    if meta.get("owner_nonce") != owner_nonce:
        return
    _remove_lock_dir(lock_path)


def replace_file(source_absolute: Path, dest_absolute: Path) -> None:
    dest_absolute.parent.mkdir(parents=True, exist_ok=True)
    if not dest_absolute.exists():
        os.replace(source_absolute, dest_absolute)
        return
    backup_path = dest_absolute.with_name(dest_absolute.name + ".uiforge_replace_backup")
    if backup_path.exists():
        backup_path.unlink()
    os.replace(dest_absolute, backup_path)
    try:
        os.replace(source_absolute, dest_absolute)
    except OSError:
        if backup_path.exists():
            os.replace(backup_path, dest_absolute)
        raise
    if backup_path.exists():
        backup_path.unlink()


def write_text_atomically(
    target_path: str | Path,
    content: str,
    source_identity_value: str = "",
    force: bool = False,
    verify: Callable[[Path], dict[str, Any]] | None = None,
) -> dict[str, Any]:
    absolute = fs_path(target_path)
    absolute.parent.mkdir(parents=True, exist_ok=True)
    temp_path = unique_temp_path(absolute, absolute.suffix or ".tscn")
    try:
        temp_path.write_text(content, encoding="utf-8")
        if verify is not None:
            verify_result = verify(temp_path)
            if not verify_result.get("ok", True):
                temp_path.unlink(missing_ok=True)
                return {"success": False, "committed": False, "errors": verify_result.get("errors", [])}
        lock = acquire_lock(absolute)
        if not lock.get("ok"):
            temp_path.unlink(missing_ok=True)
            return {"success": False, "committed": False, "errors": lock.get("errors", [])}
        lock_path = lock.get("lock_path")
        owner_nonce = str(lock.get("owner_nonce", ""))
        try:
            if source_identity_value:
                commit_check = check_commit_replace_allowed(target_path, source_identity_value, force)
                if not commit_check.get("ok"):
                    return {"success": False, "committed": False, "errors": commit_check.get("errors", [])}
            replace_file(temp_path, absolute)
        finally:
            release_lock(lock_path, owner_nonce)
    except OSError as exc:
        temp_path.unlink(missing_ok=True)
        return {"success": False, "committed": False, "errors": [{"code": "FILE_WRITE_FAILED", "message": str(exc)}]}
    return {"success": True, "committed": True, "path": str(target_path), "errors": []}


def _transaction_paths(absolute: Path) -> dict[str, Path]:
    return {
        "backup": absolute.with_name(absolute.name + ".uiforge_backup"),
        "pending": absolute.with_name(absolute.name + ".uiforge_pending"),
        "meta": absolute.with_name(absolute.name + ".uiforge_txn"),
    }


def _write_txn_meta(meta_path: Path, payload: dict[str, Any]) -> None:
    meta_path.write_text(json.dumps(payload), encoding="utf-8")


def _read_txn_meta(meta_path: Path) -> dict[str, Any]:
    if not meta_path.exists():
        return {}
    try:
        payload = json.loads(meta_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return payload if isinstance(payload, dict) else {}


def _cleanup_txn(paths: dict[str, Path]) -> None:
    for key in ("meta", "pending"):
        paths[key].unlink(missing_ok=True)


def _file_text_hash(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return ""
    return f"sha256:{hashlib.sha256(text.encode('utf-8')).hexdigest()}"


def _json_revision_from_text(text: str) -> str:
    try:
        payload = json.loads(text)
    except json.JSONDecodeError:
        return ""
    if isinstance(payload, dict):
        return content_hash(payload)
    return ""


def _json_revision_from_file(path: Path) -> str:
    try:
        return _json_revision_from_text(path.read_text(encoding="utf-8"))
    except OSError:
        return ""


def _pending_may_promote(absolute: Path, paths: dict[str, Path], meta: dict[str, Any]) -> bool:
    if not meta:
        return False
    if str(meta.get("target", "")) != str(absolute):
        return False
    if not paths["pending"].exists():
        return False
    pending_hash = _file_text_hash(paths["pending"])
    if str(meta.get("pending_hash", "")) != pending_hash:
        return False
    stage = str(meta.get("stage", ""))
    if stage != "commit" and absolute.exists():
        return False
    if pending_hash and not str(meta.get("new_revision", "")):
        return False
    return True


def _cleanup_completed_transaction(absolute: Path, paths: dict[str, Path]) -> None:
    if not absolute.exists():
        return
    meta = _read_txn_meta(paths["meta"])
    if not meta:
        if paths["backup"].exists():
            paths["backup"].unlink(missing_ok=True)
        if paths["pending"].exists():
            paths["pending"].unlink(missing_ok=True)
        return
    live_revision = _json_revision_from_file(absolute)
    if str(meta.get("new_revision", "")) == live_revision and str(meta.get("stage", "")) == "commit":
        if paths["backup"].exists():
            paths["backup"].unlink(missing_ok=True)
        _cleanup_txn(paths)


def recover_interrupted_source(absolute: Path) -> None:
    paths = _transaction_paths(absolute)
    meta = _read_txn_meta(paths["meta"])
    if paths["pending"].exists():
        if _pending_may_promote(absolute, paths, meta):
            if absolute.exists():
                absolute.unlink()
            try:
                replace_file(paths["pending"], absolute)
            except OSError:
                if paths["backup"].exists() and not absolute.exists():
                    replace_file(paths["backup"], absolute)
        else:
            paths["pending"].unlink(missing_ok=True)
    if not absolute.exists() and paths["backup"].exists():
        replace_file(paths["backup"], absolute)
    _cleanup_txn(paths)
    _cleanup_completed_transaction(absolute, paths)


def write_source_atomically(target_path: str | Path, content: str, expected_revision: str = "") -> dict[str, Any]:
    absolute = fs_path(target_path)
    absolute.parent.mkdir(parents=True, exist_ok=True)
    lock = acquire_lock(absolute)
    if not lock.get("ok"):
        return {"success": False, "committed": False, "errors": lock.get("errors", [])}
    lock_path = lock.get("lock_path")
    owner_nonce = str(lock.get("owner_nonce", ""))
    paths = _transaction_paths(absolute)
    temp_path: Path | None = None
    try:
        recover_interrupted_source(absolute)
        if expected_revision and absolute.exists():
            current = file_revision(target_path)
            if not current.get("ok"):
                return {"success": False, "committed": False, "errors": current.get("errors", [])}
            if current.get("hash") != expected_revision:
                return {
                    "success": False,
                    "committed": False,
                    "errors": [{
                        "code": "WRITE_CONFLICT",
                        "message": f"Source changed since it was loaded; refusing to overwrite {target_path}.",
                        "path": str(target_path),
                    }],
                }
        temp_path = unique_temp_path(absolute, ".ui.json")
        temp_path.write_text(content, encoding="utf-8")
        txn_id = f"{time.time_ns()}_{os.getpid()}"
        new_revision = _json_revision_from_text(content)
        pending_hash = _file_text_hash(temp_path)
        _write_txn_meta(paths["meta"], {
            "transaction_id": txn_id,
            "target": str(absolute),
            "expected_revision": expected_revision,
            "new_revision": new_revision,
            "pending_hash": pending_hash,
            "stage": "pending",
        })
        if absolute.exists():
            paths["backup"].unlink(missing_ok=True)
            replace_file(absolute, paths["backup"])
        replace_file(temp_path, paths["pending"])
        temp_path = None
        _write_txn_meta(paths["meta"], {
            "transaction_id": txn_id,
            "target": str(absolute),
            "expected_revision": expected_revision,
            "new_revision": new_revision,
            "pending_hash": pending_hash,
            "stage": "commit",
        })
        replace_file(paths["pending"], absolute)
        paths["backup"].unlink(missing_ok=True)
        _cleanup_txn(paths)
        _cleanup_completed_transaction(absolute, paths)
    except OSError as exc:
        if paths["backup"].exists() and not absolute.exists():
            replace_file(paths["backup"], absolute)
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)
        paths["pending"].unlink(missing_ok=True)
        _cleanup_txn(paths)
        return {"success": False, "committed": False, "errors": [{"code": "FILE_WRITE_FAILED", "message": str(exc)}]}
    finally:
        release_lock(lock_path, owner_nonce)
    return {"success": True, "committed": True, "path": str(target_path), "errors": []}


def validate_scene_text_ids(text: str) -> dict[str, Any]:
    errors: list[dict[str, Any]] = []
    for match in SCENE_ID_PATTERN.finditer(text):
        resource_id = match.group(1)
        if GODOT_ID_PATTERN.fullmatch(resource_id) is None:
            errors.append({
                "code": "SCENE_RESOURCE_ID_INVALID",
                "message": f"Generated scene contains invalid Godot resource id '{resource_id}'.",
            })
    return {"ok": not errors, "errors": errors}


def verify_scene_syntax(temp_path: Path) -> dict[str, Any]:
    try:
        text = temp_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        return {"ok": False, "errors": [{"code": "VERIFY_READ_FAILED", "message": str(exc)}]}
    if "[gd_scene" not in text:
        return {"ok": False, "errors": [{"code": "SCENE_SYNTAX_INVALID", "message": "Generated scene is missing [gd_scene] header."}]}
    id_check = validate_scene_text_ids(text)
    if not id_check.get("ok", False):
        return {"ok": False, "errors": id_check.get("errors", [])}
    parsed = parse_scene_header(text)
    if not parsed.get("ok", False):
        return {"ok": False, "errors": parsed.get("errors", [{"code": "SCENE_PROVENANCE_INVALID", "message": "Generated scene has invalid provenance."}])}
    if not parsed.get("header", {}).get("trusted", False):
        return {"ok": False, "errors": [{"code": "SCENE_PROVENANCE_INVALID", "message": "Generated scene is missing trusted UIForge provenance header."}]}
    return {"ok": True, "errors": []}


def validate_authored_metadata_key(key: str) -> dict[str, Any]:
    name = str(key)
    if not name or not METADATA_IDENTIFIER.fullmatch(name):
        return {"severity": "error", "code": "METADATA_KEY_INVALID", "message": f"Metadata key '{name}' must be a Godot-safe identifier.", "node": name}
    if name.startswith(RESERVED_PREFIXES) or name in GENERATED_METADATA_KEYS:
        return {"severity": "error", "code": "METADATA_KEY_RESERVED", "message": f"Metadata key '{name}' uses a reserved namespace.", "node": name}
    return {}


def validate_godot_override(property_name: str, native_type: str = "") -> dict[str, Any]:
    name = str(property_name)
    if not name or any(ch in name for ch in "\n\r="):
        return {"severity": "error", "code": "GODOT_OVERRIDE_INVALID", "message": f"Property path '{name}' contains invalid syntax.", "node": ""}
    if name.startswith("metadata/"):
        return {"severity": "error", "code": "GODOT_OVERRIDE_FORBIDDEN", "message": "Cannot write metadata through godot_overrides.", "node": ""}
    lowered = name.lower()
    if "script" in lowered or name in GENERATED_METADATA_KEYS:
        return {"severity": "error", "code": "GODOT_OVERRIDE_UNSAFE", "message": f"Property '{name}' is blocked by default.", "node": ""}
    if name.startswith("theme_override_") and "/" in name:
        return {}
    if "/" in name:
        return {"severity": "error", "code": "GODOT_OVERRIDE_UNKNOWN", "message": f"Unknown or unsupported property path '{name}'.", "node": ""}
    return {}


def types_compatible(actual: str, requested: str) -> bool:
    if actual == requested:
        return True
    allowed = FALLBACK_COMPATIBILITY.get(requested, set())
    return actual in allowed


def resource_id_part(value: str) -> str:
    canonical = str(value)
    if not canonical:
        return "node"
    return f"id_{canonical.encode('utf-8').hex()}"


def validate_external_resource(path: str, resource_type: str, property_name: str, node_id: str = "") -> dict[str, Any]:
    if not path.startswith("res://") or any(ch in path for ch in "\n\r\""):
        return {"severity": "error", "code": "RESOURCE_PATH_INVALID", "message": "External resource path must begin with res://.", "node": node_id, "property": property_name}
    extension = Path(path).suffix.lower()
    if extension in BLOCKED_RESOURCE_EXTENSIONS:
        return {"severity": "error", "code": "RESOURCE_TYPE_BLOCKED", "message": f"Resource path '{path}' uses blocked extension '{extension}'.", "node": node_id, "property": property_name}
    if resource_type in BLOCKED_RESOURCE_TYPES:
        return {"severity": "error", "code": "RESOURCE_TYPE_BLOCKED", "message": f"Resource type '{resource_type}' is blocked by default.", "node": node_id, "property": property_name}
    if "script" in property_name.lower():
        return {"severity": "error", "code": "RESOURCE_TYPE_BLOCKED", "message": f"Resource property '{property_name}' is blocked by default.", "node": node_id, "property": property_name}
    if resource_type and resource_type not in ALLOWED_RESOURCE_TYPES:
        return {"severity": "error", "code": "RESOURCE_TYPE_UNKNOWN", "message": f"Resource type '{resource_type}' is not in the UIForge whitelist.", "node": node_id, "property": property_name}
    return {}


def is_valid_theme_identifier(theme_name: str) -> bool:
    normalized = str(theme_name).strip()
    if not normalized or normalized != theme_name:
        return False
    if any(ch in normalized for ch in ("/", "\\", ".", "..")):
        return False
    if any(ord(ch) < 32 for ch in normalized):
        return False
    return THEME_IDENTIFIER.fullmatch(normalized) is not None


def available_theme_names() -> list[str]:
    theme_dir = ROOT / "addons/uiforge/themes"
    if not theme_dir.exists():
        return []
    return sorted(path.name.removesuffix(".theme.json") for path in theme_dir.glob("*.theme.json"))


def load_theme_checked(theme_name: str) -> dict[str, Any]:
    normalized = str(theme_name).strip()
    if not normalized:
        return {"theme": None, "errors": [{"severity": "error", "code": "THEME_NOT_FOUND", "message": "Document theme name is required."}]}
    if not is_valid_theme_identifier(normalized):
        return {
            "theme": None,
            "errors": [{
                "severity": "error",
                "code": "THEME_NAME_INVALID",
                "message": f"Theme name '{normalized}' is not a valid identifier.",
                "recommendation": "Use an exact theme id from addons/uiforge/themes/*.theme.json.",
            }],
        }
    available = available_theme_names()
    if normalized not in available:
        return {
            "theme": None,
            "errors": [{
                "severity": "error",
                "code": "THEME_NOT_FOUND",
                "message": f"Theme '{normalized}' was not found.",
                "recommendation": f"Choose one of: {', '.join(available)}.",
            }],
        }
    path = ROOT / f"addons/uiforge/themes/{normalized}.theme.json"
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return {"theme": None, "errors": [{"severity": "error", "code": "THEME_PARSE_ERROR", "message": str(exc), "line": exc.lineno}]}
    if not isinstance(payload, dict):
        return {"theme": None, "errors": [{"severity": "error", "code": "THEME_PARSE_ERROR", "message": "Theme file must contain an object."}]}
    return {"theme": payload, "errors": []}
